version: '3'

services:

    nginx:
        build: 
            context: ./nginx
            dockerfile: Dockerfile.node.prod
        container_name: nginx    
        ports: 
            - "80:80"
        networks: 
            -  net_bethehero    
        tty: true
        depends_on: 
            - app           

    app:
        build: 
            context: ./app2/beTheHero/frontend
            dockerfile: Dockerfile
        container_name: app
        entrypoint: yarn start
        networks: 
            - net_bethehero  
        tty: true 
        depends_on: 
            - api    
    
    api:
        build: 
            context: ./app2/beTheHero/backend
            dockerfile: Dockerfile
        container_name: api
        entrypoint: yarn start-prod
        tty: true
        networks: 
            - net_bethehero

        
networks: 
    net_bethehero:
        driver: bridge  

         
